language: node_js
node_js:
  - "lts/*"
services: mysql
cache:
  directories:
    - node_modules
before_install:
  - mysql -e 'CREATE DATABASE cho7;'
  - cd client
script:
  - cd ../server
  - npm install
  - echo '{"host":"127.0.0.1","user":"root","database":"cho7"}' > db.json
  - node init_db.js 