language:
  - node_js
node_js:
  - "lts/*"
cache:
  - npm
jobs:
  include:
    - stage: test
      services: mysql
      script:
        - mysql -e 'CREATE DATABASE cho7;'
        - yarn add wait-on -g
        - yarn add concurrently -g
        - yarn add nodemon -g
        - yarn install-all
        - echo '{"host":"127.0.0.1","user":"root","database":"cho7"}' > server/db/db-identifiants.json
        - node server/db/init_db.js
        - yarn start & wait-on http://localhost:3000
        - cd client
        - cypress run
    - stage: test
      addons:
        sonarcloud:
          organisation: "kevindelcourt-github"
        token:
          secure: ${SONAR_TOKEN}
      script: sonar-scanner
    - stage: deployment
      script: echo "hi"
