version: "3"
services:
  web:
    build: ./client
    ports:
      - "80:80"
  back:
    build: ./server
    ports:
      - "443:8180"
  mysql:
    build: ./server/db/mysql/
    ports:
      - "3306:3306"
      - "33060:33060"